---

roles:

  - name: jusanherndon.packages
  - name: jusanherndon.git_config
  - name: jusanherndon.local_settings
  - name: jusanherndon.services
  - name: jusanherndon.user_config

collections:
  
  - name: community.general
    url: https://galaxy.ansible.com
