---
- name: git-config user name
  community.general.git_config: 
    name: user.name
    scope: system
    value: "{{ user_name }}"

- name: git-config email
  community.general.git_config: 
    name: user.email
    scope: system
    value: "{{ user_email}}"
       
- name: git-config editor
  community.general.git_config: 
    name: core.editor
    scope: system
    value: "{{ user_editor }}" 

- name: github cli
  become_user: "{{ user }}"
  shell:
    cmd: gh config set -h github.com git_protocol ssh
