---
- name: git-config user name
  community.general.git_config: 
    name: user.name
    scope: system
    value: "{{ user_name }}"

- name: git-config email
  community.general.git_config: 
    name: user.email
    scope: system
    value: "{{ user_email}}"
       
- name: git-config editor
  community.general.git_config: 
    name: core.editor
    scope: system
    value: "{{ user_editor }}" 

- name: git-config merge tool
  community.general.git_config: 
    name: merge.tool
    scope: system
    value: "{{ user_mergetool }}" 

- name: git-config conflict style
  community.general.git_config: 
    name: merge.conflictstyle
    scope: system
    value: "{{ user_conflictstyle }}" 

- name: git-config merge tool prompt
  community.general.git_config: 
    name: mergetool.prompt
    scope: system
    value: "{{ user_mergetool_prompt }}" 

- name: github cli
  become_user: "{{ user }}"
  shell:
    cmd: gh config set -h github.com git_protocol ssh
