---
- name: git-config user name
  community.general.git_config: 
    name: user.name
    value: "{{ user_name }}"

- name: git-config email
  community.general.git_config: 
    name: user.email
    value: "{{ user_email}}"
       
- name: git-config editor
  community.general.git_config: 
    name: core.editor
    value: "{{ user_editor }}" 
