---
- name: git-config user name
  community.general.git_config: 
    name: user.name
    scope: system
    value: "Justin Herndon"

- name: git-config email
  community.general.git_config: 
    name: user.email
    scope: system
    value: "{{ user_email}}"
       
- name: git-config editor
  community.general.git_config: 
    name: core.editor
    scope: system
    value: "{{ user_editor }}" 
