---

- name: Changing default user settings
  user:
    name: "{{ user }}"
    state: present
    password: "{{ password | password_hash('sha512') }}"
    shell: "{{ shell }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/{{ ssh_public_key }}"
    groups: wheel
    append: yes
